services:
  app:
    build: .
    container_name: chatbot_clima_node
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true 
    tty: true
    ports:
      - "9090:9090"
volumes:
  node_modules:
